### ISSUE TITLE
how to run entire enviroment for local dev?

### ISSUE THREAD

**Issue by AlexiaChen** [Abracadabra-money/magic-internet-money#93]
the entire enviroment includes all of frontend and contracts. the contracts can deploy on local blockchain likes ganeche for local debuging and testing? 

```bash
yarn node  
```

This is run standalone hardhat network for preparing local deploy

Where is my-deploy.ts for deploying entire the project?  as follows: 

```bash
npx hardhat run --network localhost scripts/deploy.ts
```

@0xCalibur    Hi, Any suggestions? I need you help, Thanks!

**Comment by AlexiaChen** [comment]
Does not support hardhat network?  cause I found this snippet in `archive/deploy` dir：

```ts
if (network.name !== "hardhat") {
  deployFunction.skip = ({ getChainId }) =>
    new Promise((resolve, reject) => {
      try {
        getChainId().then((chainId) => {
          resolve(chainId !== "43114");
        });
      } catch (error) {
        reject(error);
      }
    });
}
```

@0xCalibur

**Comment by AlexiaChen** [comment]
Seems you use https://github.com/wighawag/hardhat-deploy#deploy-scripts to deploy contracts, I'm trying to figure it out

**Comment by 0xCalibur** [comment]
We don't deploy-all-locally, instead we usually fork at a given block inside tests and deploy new contracts from there. If you want to have a full local env that represent the current abracadabra state, e.g for UI dev, you should probably fork with ganache, the desired chain / block and connect locally with your wallet. 

I suggest you take a look at anvil instead of ganache:
```anvil --fork-url <rpc_supporting_full_archive> --fork-block-number <block_number> --block-time 13```

Also, this is the repo I'm using now: https://github.com/Abracadabra-money/abracadabra-money-foundry

**Comment by AlexiaChen** [comment]
> We don't deploy-all-locally, instead we usually fork at a given block inside tests and deploy new contracts from there. If you want to have a full local env that represent the current abracadabra state, e.g for UI dev, you should probably fork with ganache, the desired chain / block and connect locally with your wallet.
> 
> I suggest you take a look at anvil instead of ganache: `anvil --fork-url <rpc_supporting_full_archive> --fork-block-number <block_number> --block-time 13`
> 
> Also, this is the repo I'm using now: https://github.com/Abracadabra-money/abracadabra-money-foundry

@0xCalibur 

First of all, thank you for your patience in replying.

Then a new question comes up:

My goal is that I just want to get this whole project up and running, with a front-end that can debug it, and can print some logs inside the contract so it's easier to analyze the logic of the contract code. If it don't provide all localized deployments, how should I start to do some customization of the project? Because of the customization, I definitely have to run the whole project to see the effect of my modified contract output likes research others open-sourced project. just run the whole project as first for debugging and learning

It's like this project is already more complex and you abandoned `hardhat` so you're using `foundry` to build this whole project again?

**Comment by 0xCalibur** [comment]
There's nothing as such, since abra repo is more like a factory: New contracts are created, tested, deployed and then archived. You can add your own scripts to redeploy everything from scratch but what I would do instead is fork mainnet and then try use `anvil_setCode` to replace the code by local versions you wanna experiment with.

Also, there's tenderly which allows you to create fork and have an rpc endpoint and then you can debug the transactions you do.

Good luck
